version: '2.4'

services:

  chrome:
    image: jess/chrome
    container_name: "jkmq-chrome"
    environment:
      - DISPLAY=unix$DISPLAY
      - SVGA_VGPU10=0
    cpuset: "0"
    mem_limit: "512mb"
    devices:
      - "/dev/snd"
      - "/dev/dri"
    security_opt:
      - "seccomp=$HOME/chrome.json"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "/dev/shm:/dev/shm" 
    networks:
     - jkmq-net

networks:
  jkmq-net:
    name: jkmq-net
  